### ISSUE TITLE
Release v0.11 for PHP 7.4 support

### ISSUE THREAD

**Issue by martenb** [ninjify/coding-standard#23]
When it will be ready?

**Comment by mabar** [comment]
Isn't it already done?

https://github.com/ninjify/coding-standard/releases/tag/v0.10

**Comment by martenb** [comment]
Sorry, it's about month, when i was testing this. I think, the problem was with

"Requires slevomat/coding-standard ~6.0.5".. Not ^6.0.5 which is in master..

**Comment by f3l1x** [comment]
Hey @martenb. Thanks for pinging us. We should definitely work on PHP 7.4 support. I hope during july it could be done.

At this moment you can test it using composer aliasing.

```
{
	"require-dev": {
		"ninjify/qa": "^0.11.0",
		"ninjify/coding-standard": "dev-master as 0.10.0"
	}
}

**Comment by martenb** [comment]
@f3l1x thanks for the info.

**Comment by martenb** [comment]
Any progress with this?

**Comment by f3l1x** [comment]
Yep, we're working on it. Stay tuned please. :-)

**Comment by dakorpar** [comment]
This is getting really important now, since php 8.0 is comming out and we can't use old version anymore...

**Comment by f3l1x** [comment]
It's done. It works on PHP 7.1 => 8.0. Tested on contributte/image-storage (https://github.com/contributte/image-storage/commit/bda485b87188a7ce272285826edad699df4c3fe3).

```json
{
  "require-dev": {
    "ninjify/qa": "^0.12",
    "ninjify/nunjuck": "^0.4.0",
 }
}
```
